---
title: "FMM"
author: "Megan Sporre"
date: "March 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
paternal <- read.csv("../Data/kichler_paternal.csv")
paternal[is.na(paternal)] = 0         #change any columns with no value (NA) to 0
#list of broods with more than 2 paternal alleles at any given locus
MP <- apply(paternal[ ,grep("pat", names(paternal))], 1, function(x) 1*any(x>2))  

#create data frame of all broods
Mult.Pat <- as.data.frame(cbind.data.frame(paternal$Brood_ID, MP))            
colnames(Mult.Pat) <- c("Brood_ID", "MP")         #rename columns of data frame



Pm <- sum(Mult.Pat$MP) / length(Mult.Pat$MP)
Pm #observed proportion of broods with multiple paternity

#calculate minimum number of sires for each brood
max_palleles <- apply(paternal[ ,grep("pat_",names(paternal))], 1, FUN=max)
min_sires <- max_palleles / 2

#create data frame that indicates minimum number of sires for each brood
F <- as.data.frame(cbind.data.frame(paternal$Brood_ID, ceiling(min_sires)))    
colnames(F) <- c("Brood_ID", "F") 





#DETERMINE ALLELE FREQUENICUES FOR ALL LOCI FROM MATERNAL AND OFFSPRING ALLELES
maternal <- read.csv("../Data/kichler_maternal.csv", as.is = T)
offspring <- read.csv("../Data/kichler_offspring.csv", as.is = T)


rawalleles <- rbind(maternal, offspring[ ,-3])
nloc = ((dim(rawalleles)[2]-2) / 2)
lst = vector("list", nloc)
for (i in 0:(nloc - 1))
{
  #print(2+((2*i)+1):((2*i)+2)) #printing the column numbers that function is using
temp = rawalleles[ ,2+((2*i)+1):((2*i)+2)]
tb1 <- unlist(temp)
tb1 = tb1[tb1!=""]
tbl <- table(tb1)
tbl = tbl[tbl>0]
lst[[i+1]] = data.frame(frq = tbl / sum(tbl))
}


mgenos <- maternal[,-c(1:2)]

#Read in skew data - for know is a known prior may be able to incorporate calculating it at a later date
sk <- read.csv("../Data/skew.csv")

```
```{r}
library(dplyr)

#rename lst as af (allele frequencies)
af = lst

#create a data frame of offspring per brood
Cb <- data.frame(table(offspring$Brood_ID))
names(Cb) = c("Brood_ID", "Cb")



# for each of B broods, generate genotypes for F sires based on population allele frequencies
sires <- with(F, rep(Brood_ID, times = F))
sire_genotypes <- data.frame(sires)
sire_genotypes[ ,colnames(maternal[ ,-c(1:2)])] = NA

# FLOW CHART A
#runs extremely slow

#increment fmm by .01
domain = seq(0, 1, .01)
cnt=1
fmm=vector("list",length(domain))
for (f in domain)
{
 #create 1000 pseudo broods 
  numiter=1000
  lst=vector("list",numiter)
for (j in 1:numiter)
{
#create sire genotypes uning population allele frequencies for each loci
for (i in 0:(nloc - 1))
  sire_genotypes[ ,1+((2*i)+1):((2*i)+2)] = sample(af[[i+1]][ ,1] ,2*length(sires), prob = af[[i+1]][ ,2], replace = T )

#create pseudobrood by choosing alleles from mother and father for each offspring
pseudo_broods = NULL
for (b in Cb$Brood_ID)
{
  sires1 = sire_genotypes[sire_genotypes$sires == b, ]
  rn = dim(sires1)[1]
  
  maternal1 = maternal[maternal$Brood_ID == b, ]
  #print(Cb$Cb[Cb$Brood_ID==b])
    for (r in 1:Cb$Cb[Cb$Brood_ID == b])
  {
    #select sire based on paternal skew and observed number of sires for each brood
       if (rn > 1)
    {sirerow = sample(1:dim(sires1)[1], 1, prob = sk[ ,1])} else 
    {sirerow = 1}
      pseudo_ogeno <- rep(-1, dim(maternal1)[2]-2)
      for (i in 0:(nloc - 1))
      {
        mloc = maternal1[ ,2+(2*i+1):(2*i+2)]
        ploc = sires1[sirerow, 1+(2*i+1):(2*i+2)]
        mallele = unlist(sample(mloc, 1))
        pallele = unlist(sample(ploc, 1))
        oloc = as.numeric(c(mallele, pallele))
        pseudo_ogeno[(2*i+1):(2*i+2)] = oloc
      }
      pseudo_broods = rbind(pseudo_broods,
                          data.frame(Brood_ID = b , matrix(pseudo_ogeno, nrow = 1)))
  #print(b)
     #print(r) 
  #print(sires1[sirerow,"sires"])
      #count different alleles found within each broods at each locus
     allele_counts <- pseudo_broods%>%group_by(Brood_ID)%>%summarise_all(.funs=function(x){length(unique(x))})
    }
}
#create vector for number of paternal alleles at each locus for each brood
        palleles <- allele_counts[ ,as.logical((1:dim(allele_counts)[2])%%2)]    
 #list of broods with more than 2 paternal alleles at any given locus       
        MP_pseudo <- apply(palleles[ ,-1], 1, function(x) as.numeric(sum(x>2)>0))    
        
        Pm_pseudo <- sum(MP_pseudo)/length(MP_pseudo) #proportion of broods with multiple paternity

#print(Pm_pseudo) 
#pm = lst[j]
lst[j] <- Pm_pseudo
#print(paste("Pm_pseudo for iteration",j,":",Pm_pseudo))
} #for (j in 1:5)
  #print(unlist(lst))
  #print(f)
  #print(unlist(lst)/f)
  
  
fmm[[cnt]] <- unlist(lst)/f
 cnt = cnt+1

} #for (f in seq(0, .02, .01))
fmm

unlist(fmm)


```

```{r}
#WORK IN PROGRESS

#EQUATION 3

##Define Prior
p <- seq(0, 1, by = 0.01)
prior <- 1 / 101 + 0 * p
plot(p, prior, type="h", main="Prior Distribution")

##define integrated function
freq_estimate <- function(fmm,fmm1) {((fmm)*(prior)/("normalization constant"))*fmm1}
##integrate function from 0 to 1
integrate(freq_estimate, lower = 0, upper = 1)
      #do we use pseudo_pm or our observed Pm




```
